# 사용
#security:
#  user:
#    name: user
#    password: test

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.validation.mode: none
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        show_sql: true
        use_sql_comments: false
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    rest:
      base-path: /api

logging:
  path: /practice/LOG/oauth
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG
      hibernate:
        SQL: DEBUG
        type: DEBUG
